services:
  ssVPN:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ssVPN
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      # پورت اتصال کاربران SSH
      - "${INCOMMING_PORT:-2222}:22"
      # پورت UDP Forwarding برای BadVPN
      - "7300:7300/udp"
    volumes:
      # مسیر ذخیره همیشگی دیتای کاربران
      - ssVPN_data:/etc/vpn_users
    environment:
      - ADMIN_USER=${ADMIN_USER:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - DIRECT_HOST=${DIRECT_HOST}
      - INCOMMING_PORT=${INCOMMING_PORT:-2222}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_ADMIN_ID=${TELEGRAM_ADMIN_ID}
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

volumes:
  ssVPN_data:
